#ifdef LANG_IT

#define _M_AC001 "Porta USB pronta"
#define _M_AC002 "inizializzazione..."
#define _M_AC003 "...inizializzazione modulo GSM..."
#define _M_AC004 "...inizializzazione orologio..."
#define _M_AC005 " fallita!"
#define _M_AC006 ": fatto!"
#define _M_AC0A4 "Sincronizzazione orologio"

#define _M_LM001 "Riprovo sincronizzazione orologio"
#define _M_LM002 "Avvio inizializzazione"

#define _M_PH001 "Avviso sconosciuto: "
#define _M_PH002 "Comando \""
#define _M_PH003 "\" fallito:"
#define _M_PH004 "Sincronizzazione autobaud"
#define _M_PH005 "Verifica avvio SIM800"
#define _M_PH006 "Impostazione parametri AT SIM800 "
#define _M_PH0A7 "Modulo GSM "
#define _M_PH007 "avviato"
#define _M_PH008 "non funzionante"

#define _M_SM001 "Comando \""
#define _M_SM002 "\" eseguito"
#define _M_SM003 "\" fallito"
#define _M_SM0A4 " cancellato."
#define _M_SM005 "Nome server APN"
#define _M_SM0B5 "Prego fornire"
#define _M_SM0A5 " troppo lungo: massimo 20 caratteri."
#define _M_SM008 "Fuso orario va da \"-47\" a \"+48\"."
#define _M_SM009 "Indica la differenza, espressa in quarti d'ora, tra il fuso locale e GMT."
#define _M_SM010 ", es. \"NTP time.inrim.it\" oppure \"NTP 193.204.114.105\""
#define _M_SM011 "Nome server NTP"
#define _M_SM012 " registrato."
#define _M_SM014 "Numero di telefono"
#define _M_SM015 " non trovato."
#define _M_SM024 "LivGSM= \""
#define _M_SM025 "Clk ok\n"
#define _M_SM026 "No Clock\n"
#define _M_SM027 "G.Led (LSC)="
#define _M_SM028 "L.SMS="
#define _M_SM029 "St.tel.="
#define _M_SM030 "Canc.="
#define _M_SM031 "Com.tel="
#define _M_SM032 "T.Ciclo="
#define _M_SM033 "Comando non riconosciuto."
#define _M_SM034 "Acccen="
#define _M_SM035 "Master gia' registrato."
#define _M_SM036 "Master ("
#define _M_SM037 ") registrato correttamente. "
#define _M_SM038 "Gia' registrato come Master"
#define _M_SM039 "Data scadenza errata: deve avere formato YY/MM/DD o essere assente"
#define _M_SM040 "Utente ("
#define _M_SM041 "Primi "
#define _M_SM042 " in rubrica:\n"
#define _M_SM043 "\nAVVISO: l'orologio di sistema non puo' essere aggiornato: non verra' gestita la data scadenza"
#define _M_SM044 ":\n   "
#define _M_SM045 "Fuso orario"
#define _M_SM046 " di "

#endif
