#ifdef LANG_EN

#define _M_AC001 "USB port ready"
#define _M_AC002 "initialising..."
#define _M_AC003 "...initialising GSM module..."
#define _M_AC004 "...initialising clock..."
#define _M_AC005 " went wrong!"
#define _M_AC006 ": done!"
#define _M_AC0A4 "Clock setup"

#define _M_LM001 "Retry clock setup"
#define _M_LM002 "Going to initializing"

#define _M_PH001 "Unknown alert: "
#define _M_PH002 "command \""
#define _M_PH003 "\" failed:"
#define _M_PH004 "Autobaud syncing"
#define _M_PH005 "Checking SIM800 device wakeup"
#define _M_PH006 "setting SIM800 AT parameters "
#define _M_PH0A7 "GSM module "
#define _M_PH007 "on"
#define _M_PH008 "NOT WORKING"

#define _M_SM001 "Command \""
#define _M_SM002 "\" done"
#define _M_SM003 "\" failed"
#define _M_SM0A4 " deleted."
#define _M_SM005 "APN server name"
#define _M_SM0B5 "Please provide "
#define _M_SM0A5 " too long: max 20 characters."
#define _M_SM008 "Time Zone is from \"-47\" to \"+48\"."
#define _M_SM009 "It indicates the difference, expressed in quarters of an hour, between the local time and GMT."
#define _M_SM010 " e.g. \"NTP time.inrim.it\" or \"NTP 193.204.114.105\""
#define _M_SM011 "NTP server address"
#define _M_SM012 " set."
#define _M_SM014 "Phone Number"
#define _M_SM015 " not found."
#define _M_SM024 "L.level= \""
#define _M_SM025 "Clk set\n"
#define _M_SM026 "No Clock\n"
#define _M_SM027 "Ledmgmt(LSG)="
#define _M_SM028 "Sms L.="
#define _M_SM029 "PhoChk="
#define _M_SM030 "GateMgr="
#define _M_SM031 "PhoReq="
#define _M_SM032 "L.time="
#define _M_SM033 "Command not recognized."
#define _M_SM034 "Uptime="
#define _M_SM035 "Master already set."
#define _M_SM036 "Master ("
#define _M_SM037 ") correctly registred."
#define _M_SM038 "Already registred as Master"
#define _M_SM039 "Expiry date bad format: must be either YY/MM/DD format or not defined"
#define _M_SM040 "User ("
#define _M_SM041 "First "
#define _M_SM042 "S in phonebook:\n"
#define _M_SM043 "\nWARNING: can't update system clock: expiring date won't work"
#define _M_SM044 ":\n   "
#define _M_SM045 "Time Zone"
#define _M_SM046 " of "

#endif
